### PR TITLE
Introspection on sent message

### PR DESCRIPTION
**Pull request by reyostallenberg**
Make it possible to get data form the sent message

### CODE REVIEW

**Comment by RonRademaker** [comment]
Thanks, because `$this->message` can also be set from other places, I'd prefer a simple `getMessage` getter so you can retrieve it for inspection. I think that's more consistent than having some send method returning nothing while others return the message.

**Comment by reyostallenberg** [comment]
@RonRademaker Changed to your proposal

**Review by RonRademaker — APPROVED** [review]

**Comment by RonRademaker** [comment]
Thanks, I've also tagged a release with this new feature: https://github.com/RonRademaker/Mailer/releases/tag/1.2.0

**Comment by reyostallenberg** [comment]
Tnx

**Pull request merged**
